apiVersion: apps/v1
kind: Deployment
metadata:
  name: moapp01
spec:
  selector:
    matchLabels:
      app: moapp01
  template:
    metadata:
      labels:
        app: moapp01
    spec:
      containers:
      - name: sidapp01
        image: sbacr02.azurecr.io/moapp01:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5178
